import { Texture } from "@babylonjs/core/Materials/Textures/texture";
import { SpriteManager } from "@babylonjs/core/Sprites/spriteManager";
import type { Scene } from "@babylonjs/core/scene";
// side-effect: registers the sprite scene component so SpriteManager renders
import "@babylonjs/core/Sprites/spriteSceneComponent";

/**
 * Shared pixel-art sprite atlas for the 2D top-down render layer. ONE
 * `SpriteManager` on `public/game/sprites.png` (generated by
 * scripts/gen-sprites.mjs) backs every on-field sprite — enemies, the hero
 * turret, powerup crystals — sampled NEAREST so the pixels stay crisp under the
 * orthographic camera. The atlas is a uniform 64px grid; cell indices below
 * MUST match the committed sprites.json manifest (row-major, 8 cols).
 */

export const ATLAS_CELL = 64; // uniform grid cell (8 cols × 3 rows in sprites.json)
const ATLAS_URL = "/game/sprites.png";

/** cellIndex map — mirrors public/game/sprites.json `cells`. */
export const CELLS = {
	husk: [0, 1],
	darter: [2, 3],
	wraith: [4, 5],
	charger: [6, 7],
	weaver: [8, 9],
	brood: [10, 11],
	boss: [12, 13],
	heroIdle: 14,
	heroRecoil: 15,
	dot: 16,
	crystal: 17,
} as const;

/** The two walk-cycle cells for an enemy family (falls back to husk). The id
 * prefix is the family key; `corkscrew`/`lunger` are new archetypes that reuse
 * existing family art (no new sprite cells) — darter for the corkscrew, charger
 * for the lunger. */
const WALK: Record<string, readonly [number, number]> = {
	husk: CELLS.husk,
	darter: CELLS.darter,
	wraith: CELLS.wraith,
	charger: CELLS.charger,
	weaver: CELLS.weaver,
	brood: CELLS.brood,
	boss: CELLS.boss,
	corkscrew: CELLS.darter,
	lunger: CELLS.charger,
};
export function walkCells(family: string): readonly [number, number] {
	return WALK[family] ?? CELLS.husk;
}

export type SpriteAtlas = {
	manager: SpriteManager;
	dispose(): void;
};

export function createSpriteAtlas(scene: Scene, capacity = 64): SpriteAtlas {
	const manager = new SpriteManager(
		"sprite-atlas",
		ATLAS_URL,
		capacity,
		{ width: ATLAS_CELL, height: ATLAS_CELL },
		scene,
	);
	// crisp pixels: no bilinear smoothing anywhere on the atlas
	manager.texture.updateSamplingMode(Texture.NEAREST_SAMPLINGMODE);
	// draw sprites above the ground/decals but the label planes still overlay them
	manager.renderingGroupId = 0;
	// the atlas is authored with a fixed cell grid
	manager.cellWidth = ATLAS_CELL;
	manager.cellHeight = ATLAS_CELL;
	return {
		manager,
		dispose() {
			manager.dispose();
		},
	};
}
